# Generated by Django 4.1 on 2022-11-12 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phonenum', models.PositiveIntegerField(null=True)),
                ('github', models.CharField(max_length=100, null=True)),
                ('linkedin', models.CharField(max_length=100, null=True)),
                ('insta', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=20, null=True)),
                ('Lname', models.CharField(max_length=20, null=True)),
                ('Designation', models.CharField(max_length=20)),
                ('testimonial', models.TextField(null=True)),
                ('Profilepic', models.ImageField(blank=True, null=True, upload_to='faculty_profile/')),
                ('Specialisation', models.CharField(max_length=20)),
                ('fk_contactid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='committee_api.contact_info')),
            ],
        ),
        migrations.CreateModel(
            name='Exmembers',
            fields=[
                ('Fname', models.CharField(max_length=20, null=True)),
                ('Lname', models.CharField(max_length=20, null=True)),
                ('SapId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Position', models.IntegerField(choices=[('The big three', ((1, 'Chair person'), (2, 'Co-chair person'), (3, 'Admin & secretary'))), ('Tech', ((4, 'ML Head'), (5, 'Tech Head'))), ('Non-Tech', ((6, 'Creative Head'), (7, 'Events & PR Head'), (8, 'Marketing Head'))), ('Founder', ((9, 'Founder'),))])),
                ('testimonial', models.TextField(null=True)),
                ('Profilepic', models.ImageField(blank=True, null=True, upload_to='exmembers_profile/')),
                ('fk_contactid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='committee_api.contact_info')),
            ],
        ),
        migrations.CreateModel(
            name='CoreCommittee',
            fields=[
                ('Fname', models.CharField(max_length=20, null=True)),
                ('Lname', models.CharField(max_length=20, null=True)),
                ('SapId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Position', models.IntegerField(choices=[('The big three', ((1, 'Chair person'), (2, 'Co-chair person'), (3, 'Admin & secretary'))), ('Tech', ((4, 'ML Head'), (5, 'Tech Head'))), ('Non-Tech', ((6, 'Creative Head'), (7, 'Events & PR Head'), (8, 'Marketing Head')))])),
                ('testimonial', models.TextField(null=True)),
                ('Profilepic', models.ImageField(blank=True, null=True, upload_to='core_profile/')),
                ('fk_contactid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='committee_api.contact_info')),
            ],
        ),
    ]
