# Generated by Django 4.1 on 2022-11-14 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committee_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('sponsors', models.TextField(null=True)),
                ('budget', models.IntegerField(null=True)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='multi_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='committee_api.event')),
            ],
        ),
    ]
